### ISSUE TITLE
Its good if this was an actual JQuery Plugin

### ISSUE THREAD

**Issue by kasvith** [sanjayaharshana/AnimTrap#14]
# jQuery Plugin is needed

Its obvious that this plugin is not binding to jQuery itself.
We need let users to select what element should display the rain, so i suggest to refactor this to be used as like

$('#my-custom-id-div').rain()

**Comment by sanjayaharshana** [comment]
yeah..modified for JQueary Plugin, so when you want to add rain effect your html element. frist thing you should 

`<script type="text/javascript">
  $( "#my-custom-id-div" ).rain({
});
</script>`

**Comment by kasvith** [comment]
You can close issue now, please mention PR for it
